# Welcome to Jekyll!

title: Threonine Design
email: contact@threoninedesign.fr
description: Threonine | Illustrer la science
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
# We're using formspree.io for form handling, paste your formspree url below
formspreeFormUrl: "https://formspree.io/myykjpje"

# Build settings
gems:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 2
  permalink: '/blog/:num/'
  sort_field: 'date'
  sort_reverse: true

sass:
  sass_dir: _scss/
  style: compressed

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Navigation (remember to remove the redondant /threonine)
navigation:
  - title: Accueil
    url: /
  - title: A propos
    url: /about
  - title: Portfolio
    url: /portfolio
  - title: CV
    url: /cv
  - title: Contact
    url: /contact
    tag: special

# Call to action
call-to-action:
  enable                : true
  background_image      : "images/backgrounds/cta-background2.jpg"
  title                 : "Travaillons ensemble !"
  primary_button        : "Contactez-moi"
  primary_button_url    : "contact"
  secondary_button      : "Revoir mon travail"
  secondary_button_url  : "portfolio"

# Footer
footer:
  contactInfo:
    title   : "Informations de contact"
    address : "Anne-Claire Godet </br> 220 chemin de Montabon <br/> 38660 LE TOUVET <br/> FRANCE"
    email   : "contact@threoninedesign.fr"
  sitemap:
    title: "Plan du site"
    link: 
      - name  : "A propos"
        url   : "/about"
      - name  : "Portfolio"
        url   : "/portfolio"
      - name  : "CV"
        url   : "/cv"
      - name  : "Contact"
        url   : "/contact"
  social:
    title: "Réseaux sociaux"
    link: 
      - name  : "Linkedin"
        url   : "https://www.linkedin.com/in/anne-claire-godet-031/"
      - name  : "Instagram"
        url   : "https://www.instagram.com/threo.nine/"
      - name  : "Behance"
        url   : "https://www.behance.net/threoninedesign"
      - name  : "Facebook"
        url   : "https://www.facebook.com/threonine.design"
  service:
    title: "J'aide les chercheurs à:"
    description: "Libérer du temps pour se consacrer à leur coeur de métier <br/> Mettre en valeur leurs résultats </br> Faire passer leur message"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
